/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p06_14873443_21145466;

/**
 *
 * @author wnd5547
 */
public class PurchaseTicketsJFrame extends javax.swing.JFrame {

    Seats seatsObj;
    String showChoice;
    String dateChoice;
    /**
     * Creates new form PurchaseTicketsJFrame
     */
    public PurchaseTicketsJFrame() {
        initComponents();
        this.date1.setVisible(false);
        this.date2.setVisible(false);
        this.date3.setVisible(false);
        this.seatsObj = new Seats();
        this.invalidSeat.setVisible(false);
        this.purchased.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectShow = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectedRow = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectedCol = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        cats = new javax.swing.JButton();
        lilShop = new javax.swing.JButton();
        fiddler = new javax.swing.JButton();
        evita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        date1 = new javax.swing.JButton();
        date2 = new javax.swing.JButton();
        date3 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        invalidSeat = new javax.swing.JLabel();
        purchased = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectShow.setText("Select Show");

        jLabel1.setText("Select Row");

        jLabel2.setText("Select Column");

        selectedCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedColActionPerformed(evt);
            }
        });

        price.setText("Price: $");

        jButton1.setText("Purchase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        cats.setText("Cats");
        cats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catsActionPerformed(evt);
            }
        });

        lilShop.setText("Little Shop of Horrors");
        lilShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lilShopActionPerformed(evt);
            }
        });

        fiddler.setText("Fiddler on the Roof");
        fiddler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiddlerActionPerformed(evt);
            }
        });

        evita.setText("Evita");
        evita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evitaActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Date");

        date1.setText("date1");
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });

        date2.setText("date2");
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });

        date3.setText("date3");
        date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date3ActionPerformed(evt);
            }
        });

        submit.setText("Sumbit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        invalidSeat.setForeground(new java.awt.Color(255, 0, 0));
        invalidSeat.setText("Invalid seat!");

        purchased.setForeground(new java.awt.Color(0, 153, 0));
        purchased.setText("Purchased!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(selectShow)
                    .addComponent(jLabel1)
                    .addComponent(selectedRow)
                    .addComponent(jLabel2)
                    .addComponent(selectedCol, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(price)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchased))
                    .addComponent(cats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lilShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiddler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(evita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(18, 18, 18)
                        .addComponent(invalidSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lilShop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiddler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(evita)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date1)
                            .addComponent(date2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit)
                            .addComponent(invalidSeat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(purchased))
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectedColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedColActionPerformed

    private void catsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catsActionPerformed
        this.date1.setText("24 June");
        this.date2.setText("01 July");
        this.date3.setText("13 July");
        this.date1.setVisible(true);
        this.date2.setVisible(true);
        this.date3.setVisible(true);
        this.showChoice = "a";
    }//GEN-LAST:event_catsActionPerformed

    private void lilShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lilShopActionPerformed
        this.date1.setText("21 June");
        this.date2.setText("10 July");
        this.date3.setText("17 July");
        this.date1.setVisible(true);
        this.date2.setVisible(true);
        this.date3.setVisible(true);
        this.showChoice = "b";
    }//GEN-LAST:event_lilShopActionPerformed

    private void fiddlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiddlerActionPerformed
        this.date1.setText("12 June");
        this.date2.setText("27 June");
        this.date3.setText("07 July");
        this.date1.setVisible(true);
        this.date2.setVisible(true);
        this.date3.setVisible(true);
        this.showChoice = "c";
    }//GEN-LAST:event_fiddlerActionPerformed

    private void evitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evitaActionPerformed
        this.date1.setText("18 June");
        this.date2.setText("03 July");
        this.date3.setText("19 July");
        this.date1.setVisible(true);
        this.date2.setVisible(true);
        this.date3.setVisible(true);
        this.showChoice = "d";
    }//GEN-LAST:event_evitaActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        
        this.dateChoice = "a";
        boolean[][] choosingSeats = seatsObj.loadSeats(showChoice, dateChoice); //Load the correct show's seat array based on show and date option chosen
        this.text.setText(seatsObj.arrayString(choosingSeats));
        
    }//GEN-LAST:event_date1ActionPerformed

    public boolean isNumber(String str) {
    try {
        Integer.parseInt(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        boolean row = isNumber(this.selectedRow.getText());
        boolean col = isNumber(this.selectedCol.getText());
        
        if(row && col)
        {
            int rowNum = Integer.parseInt(this.selectedRow.getText());
            int colNum = Integer.parseInt(this.selectedCol.getText());
            
            if(rowNum < 0 || rowNum > 9)
            {
                this.invalidSeat.setVisible(true);
            }
            if(colNum < 0 || colNum > 19)
            {
                this.invalidSeat.setVisible(true);
            }
            else
            {
                this.invalidSeat.setVisible(false);
                
                if (rowNum <= 2) //Depending on which row they pick, the tickets will be different prices. Expensive in the front and cheaper at the back.
                {
                    PlatinumTicket ticket = new PlatinumTicket(rowNum);
                    ticket.calcPrice(rowNum);
                    this.price.setText("Price: $" +ticket.toString());

                } else if (rowNum > 2 && rowNum <= 5) {
                    GoldTicket ticket = new GoldTicket(rowNum);
                    ticket.calcPrice(rowNum);
                    this.price.setText("Price: $" +ticket.toString());
                    
                } else if (rowNum > 5 && rowNum <= 9) {
                    StandardTicket ticket = new StandardTicket(rowNum);
                    ticket.calcPrice(rowNum);
                    this.price.setText("Price: $" +ticket.toString());
                    
                }
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        this.dateChoice = "b";
        boolean[][] choosingSeats = seatsObj.loadSeats(showChoice, dateChoice); //Load the correct show's seat array based on show and date option chosen
        this.text.setText(seatsObj.arrayString(choosingSeats));
    }//GEN-LAST:event_date2ActionPerformed

    private void date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date3ActionPerformed
        this.dateChoice = "c";
        boolean[][] choosingSeats = seatsObj.loadSeats(showChoice, dateChoice); //Load the correct show's seat array based on show and date option chosen
        this.text.setText(seatsObj.arrayString(choosingSeats));
    }//GEN-LAST:event_date3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.purchased.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicketsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicketsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicketsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicketsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseTicketsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cats;
    private javax.swing.JButton date1;
    private javax.swing.JButton date2;
    private javax.swing.JButton date3;
    private javax.swing.JButton evita;
    private javax.swing.JButton fiddler;
    private javax.swing.JLabel invalidSeat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lilShop;
    private javax.swing.JLabel price;
    private javax.swing.JLabel purchased;
    private javax.swing.JLabel selectShow;
    private javax.swing.JTextField selectedCol;
    private javax.swing.JTextField selectedRow;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
